name: "CI"
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true
  CACHE_PATH: '**/node_modules'

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: wyvox/action@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: wyvox/action@v1
      - name: Lints
        run: pnpm lint

  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    name: "Tests"
    runs-on: "${{ matrix.platform }}"
    needs: [install_dependencies]

    steps:
    - uses: wyvox/action@v1
    - run: |
        pnpm add --global ember-cli
    - name: Tests
      run: pnpm test

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository == 'NullVoxPopuli/ember-apply' && github.ref == 'refs/heads/main'
    needs:
      - lint
      - tests

    steps:
      - uses: wyvox/action@v1
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            
